language: python

arch:
  - arm64

services:
  - docker

install: skip

script:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - export REPOSITORY=discord-alko
  - export IMAGE_TAG=latest
  - docker build -t hugis420/$REPOSITORY:$IMAGE_TAG .
  - docker push hugis420/$REPOSITORY:$IMAGE_TAG
