name: Discord Alko pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to DO CR
      if: contains(github.ref, 'refs/heads/master') || contains(github.ref, 'refs/tags/deploy-staging')
      env:
        REPOSITORY: discord-alko
        IMAGE_TAG: latest
      run: |
        doctl registry login
        docker build -t hugis420/$REPOSITORY:$IMAGE_TAG .
        docker push hugis420//$REPOSITORY:$IMAGE_TAG

